# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers

    working_directory: ~/BUH4Isite

    steps:
      - checkout

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-

      # - run:
      #     name: install dependencies
      #     command: |
      #       yarn install
      # - save_cache:
      #     paths:
      #       - ./node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}
      #
      # - run:
      #     name: build h4i site
      #     command: |
      #       yarn build
      - deploy:
          name: deploy h4i site
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -o StrictHostKeyChecking=no circleci@${H4I_SERVER_IP} 'rm -rf /var/www/hack4impactbu.com/html/'
              scp -o StrictHostKeyChecking=no -r ~/BUH4Isite circleci@${H4I_SERVER_IP}:/var/www/hack4impactbu.com/html/
            fi
